# Generated by Django 4.2.16 on 2024-09-24 12:24

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default=None, max_length=12, validators=[accounts.validators.validate_iranian_cellphone_number]),
            preserve_default=False,
        ),
    ]
