# Generated by Django 4.2.16 on 2024-10-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile/default.jpg", upload_to="profile/"
            ),
        ),
    ]
