# Generated by Django 4.2.16 on 2024-09-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_create_date_productcategorymodel_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['-created_date']},
        ),
    ]
